#+TITLE: COS 333---Missions Computing
#+DATE: January 2015

#+STARTUP: indent
#+OPTIONS: toc:nil author:nil ':t

#+LATEX_CLASS: syllabus
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage[margin=1.5in]{geometry}
#+LATEX_HEADER: \usepackage{lastpage}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \lhead{COS 333---Missions Computing}
#+LATEX_HEADER: \chead{}
#+LATEX_HEADER: \rhead{Course Syllabus}
#+LATEX_HEADER: \lfoot{January 2015}
#+LATEX_HEADER: \cfoot{}
#+LATEX_HEADER: \rfoot{Page \thepage\ of \pageref{LastPage}}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0.4pt}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0.4pt}
#+LATEX_HEADER: \renewcommand\maketitle\relax

* Instructor
*Dr. Tom Nurkkala*\\
Associate Professor, Computer Science and Engineering\\
Director, Center for Missions Computing\\
Office: Euler Science 211\\
E-Mail: =tnurkkala@cse.taylor.edu=\\
Phone: 765/998-5163\\
Hours: MW 2:00-4:00 or by appointment\\

* Introduction
Missions Computing is a course primarily intended for students in Computer Science and
Engineering who wish to engage in service-learning activities—particularly software
development—with a partner in the international missions community.

Admission to the course is by instructor permission. This course carries cross cultural
(CC) credit.
* Objectives
The Missions Computing course engages you directly in missions computing
in an international context where missions computing systems
are created or used (or both).
In particular, you will:
+ Apply your understanding of computer science and expertise in software development by
  contributing to the design, construction, enhancement, testing, deployment,
  documentation, or support of software employed directly by a missions partner.
+ Travel internationally to a missions partner location at which software and systems are
  developed, supported, or deployed in direct support of missions operations.
+ Experience the mission partner’s organization through engagement with missions staff and
  families in service, fellowship, prayer, and worship.  One goal of this experience is to
  “demystify” missions service, letting you see that your knowledge, abilities, and skills
  can be directly employed in service to the gospel.
+ Engage the local culture of the missions partner through service, evangelism, and
  mentoring under the leadership of the missions partner.
+ Understand how God superintends the advancement of computing and related technology,
  making it available to Christian technologists to obey the Great Commission and Great
  Commandments.
+ See firsthand how software and systems impact and enable the work of the missions
  partner both in the office and in the field.
+ Understand the need throughout the missions community for financial and human resources
  in support of computing and related needs.
* Content
The Missions Computing course comprises the following key elements.
** Course Preparation
Because the travel component of the course qualifies as a mission trip (more than 50% of
course activities are directly related to missions service), you are eligible to raise
tax-deductable support through Taylor University.  You are required to contact supporters
who are willing to provide prayer or financial support for the trip.  In addition, you
will:
+ Participate in team organization and information meetings facilitated by the team
  leaders.
+ Read and study technical material relevant to the missions computing project as directed
  by the team leaders.
** International Experience
The majority of the course consists of international experience serving with a missions
partner.  During this time, you will:
+ Learn about the missions partner through orientation presentations, discussion, and
  activities, usually facilitated by staff at the missions partner.
+ Acclimate to the community in which you will serve by various means, including home
  stays with mission staff, worship services, community engagement, and other activities.
+ Develop relationships with missions staff through shared service on team projects and
  through participation in normal partner activities such as team devotions, Bible study,
  corporate prayer, and the like.
+ Receive training on the software and systems with which you will be working while in
  country with the missions partner.  Typical topics include software engineering practice
  and process, languages and frameworks, logical modeling, revision control, issue
  tracking, continuous integration, and so forth.
+ Design, develop, enhance, repair, or extend software systems at the direction of the
  technical leadership at the mission.  This activity constitutes a considerable fraction
  of your time at the mission partner (typically "full time" work hours most days).
+ Enjoy and appreciate cultural, social, and ethnic diversity through travel,
  dining, sightseeing, and similar activities.
+ Reflect on your travel and service through introspection, discussion, and required
  journaling.
** Course Wrap-Up
Upon return to campus, you will:
+ Clean up and complete your journal.
+ Write and submit your final experience paper.
+ Attend and participate in any final debriefing meetings, team celebration, campus
  presentation, etc.
* Deliverables
You must submit the following deliverables on the last day of the course.
** Journal
The journal is a daily written record of your experience throughout the course, including
the time before, during, and after international travel and service.  You are expected to
make at least one entry per day, but are welcome to make more than one.  Each is to be
tagged with the date and location at which the entry was made.  These entries will be
read and evaluated by the instructor, but will not be shared with other team members
unless you authorize or encourage it.  Over the duration of the course, your journal
should include (but is not limited to):
+ Motivations for participation in the course
+ Expectations for the course prior to departure, including open questions that you hope
  to explore and answer during the course
+ Travel experience (to, from, and in the field)
+ Experience serving with the missions partner from technical, personal, social, and
  spiritual perspectives
+ Observations and insights into the culture(s) served during the trip
+ Changes in your view of culture, economics, government, technology, relationships,
  missions, theology, and spirituality (both in the international culture and at home)
+ Answers or insights into the questions you hoped to address during the course
+ Ways in which the experience altered, clarified, or informed your vocational calling as
  a computer scientist seeking to serve Jesus.
+ Aspects of the course that were important, meaningful, or just plain fun.
+ Suggestions as to how the course could be improved in the future.
** Final Experience Paper
You will write a paper about your personal experience during the course. The goal of this
paper is to reflect on your own experience in the course and how you matured as a computer
scientist and as a Christian.  Your paper should address at least the following questions.
+ What stood out to you as unexpected or otherwise significant with regard to your
  perception of a culture other than your own?
+ What insights did you gain regarding missions service in general?
+ What did you learn about yourself as it relates specifically to serving as a member of a
  missions computing team?
+ What were the most important knowledge and skills you acquired as it relates to your
  future as a computer scientist?
+ How did your experience speak to your vocational call as a Christ follower?
These questions are not intended to be exhaustive. You are encouraged to reflect in your
paper on any additional insights you gleaned from your experience.

Type your paper. Please double space. Use good spelling, grammar, punctuation, and
structure. Your paper should be 1,250 to 1,500 words long. Print your paper and submit it
to me.
* Participation
Barring sickness or injury, you are expected to attend all the meetings, activities, and
team project work throughout the course (before, during, and after our international
travel).
* Evaluation
Refer to my Periodic Table of the Grades (on Moodle) for my standard grading scheme. I
reserve the right to award a higher grade than strictly earned; outstanding contributions,
leadership, and participation figure prominently in such decisions.  Course criteria
contribute to your grade according to the following table.
#+ATTR_LTEX: :booktabes t
| Criterion                     | Weight |
|-------------------------------+--------|
|                               |    <r> |
| Mature, Christlike behavior   |    10% |
| Positive, optimistic attitude |    10% |
| Teamwork and participation    |    15% |
| Project contributions         |    30% |
| Journal                       |    20% |
| Final experience paper        |    15% |
* Academic Integrity
As a student at an institution whose goal is to honor Christ in all that it does,
I expect you to uphold the strictest standards of academic integrity.
You must do your own work, cite others when you present their work,
and never misrepresent your academic performance in any way.
Violation of these standards stains the reputations of you as a student,
Taylor as an institution,
and Jesus as our Lord.
Such a violation may result in your failing the course
and other disciplinary action by the University.
Refer to the Taylor catalog for the official statement of these ideas.

