#+TITLE: SYS 394---Information Systems Design
#+DATE: Spring, 2014

#+STARTUP: indent
#+OPTIONS: toc:nil author:nil ':t

#+LATEX_CLASS: syllabus
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage[margin=1.5in]{geometry}
#+LATEX_HEADER: \usepackage{lastpage}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \lhead{SYS 394---Information Systems Design}
#+LATEX_HEADER: \chead{}
#+LATEX_HEADER: \rhead{Course Syllabus}
#+LATEX_HEADER: \lfoot{Spring 2014}
#+LATEX_HEADER: \cfoot{}
#+LATEX_HEADER: \rfoot{Page \thepage\ of \pageref{LastPage}}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0.4pt}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0.4pt}
#+LATEX_HEADER: \renewcommand\maketitle\relax

* Instructor
*Dr. Tom Nurkkala*\\
Associate Professor, Computer Science and Engineering\\
Director, Taylor Center for Missions Computing\\
Office: Euler Science Complex 211\\
E-Mail: =tnurkkala@cse.taylor.edu=\\
Phone: 8-5163\\
Hours: MW 2:00-4:00 or by appointment\\
* Course Overview
The course focuses on the physical design and construction phases
of the system development life cycle.
Our goal is to implement a working prototype
of the system defined and analyzed in SYS 390 (ISA)
as a database-backed web application.
We will cover web and database programming, advanced SQL topics,
software project management practices, system architecture,
and related web technology.

The course comprises two hands-on, lab-heavy segments.
1. For approximately the first five weeks, we will focus on the basics of developing a
  database-backed web application. This portion of the course is designed to provide
  everyone in the class with the knowledge and skills necessary to understand and
  construct a non-trivial web application. We will cover salient topics in class, and you
  will complete a series of lab exercises that give you practice with the topic of the
  day.
2. For the remaining ten weeks of the course, you will be working on constructing a
   prototype application that implements the requirements you gathered in ISA as reflected
   in your System Requirements Specification (ISA).
* Learning Objectives
When you complete this class you should be able to:
1. Understand the importance of a formal system development methodology to information
   technology project success
2. Learn how to translate a logical design to a physical design
3. Improve user interface design skills
4. Learn agile software project management practices and tools
5. Sharpen group participation skills
6. Expand relational database skills, including SQL transactions, and stored procedures
7. Learn some technologies powering e-commerce: three-tier architecture, web pages,
   ASP.NET, Visual Basic
8. Learn and apply testing skills, including unit tests and client-side GUI tests
9. Improve presentation skills by sharing project results with the class
* Text
We will continue to use the textbook from ISA.\cite{valacich2012}
* Project
We will continue the project begun in ISA. Our goal is to build working prototypes of a
system that implements the bulk of the system you envisioned in your SRS in ISA.
** Teams
Again this semester, you will work in teams,
typically comprising 3-5 students.
Unlike ISA, however, I will select the members of the teams
in order to ensure each team has a fair balance
of technical and non-technical expertise.

I will distribute a brief survey early in the semester
that will help me gauge your technical background.
The survey also asks you to indicate who you would---and would not---like
to have on your team.
Although a good balance of skills will trump your personal preferences,
I do my best to honor your request.
** DevelopmentProcess
Teams will employ a development process
based on the standard agile process known as /Scrum/.
We will employ an iterative approach to project development
in which your team will focus on delivering
small increments of functionality
that provide both you and me a clear and demonstrable indication of your progress.

As in ISA, procrastination is the enemy.
Using an agile, iterative process forces you and your team
regularly to deliver working software,
which not only gives you a clear view of your accomplishments,
but helps stem the tide of procrastination.
** Show-and-Tell
At the end of the semester, we will have a "show and tell" time,
during which you will demonstrate your prototype application.
Our customer will be invited to join us for your demonstrations,
either in person or electronically.

Although this presentation is not nearly as formal as your final presentation in ISA,
it is nonetheless your opportunity to show off the fruit of a year of your labor.
Begin the semester with this end in mind,
and stay focused on delivering an excellent and exciting final product!
** Technology
We will be building the project prototypes using current versions
of the Microsoft tool chain.
Although Microsoft is not a favorite platform of mine,
it is ubiquitous in business and deserves your careful attention.

1. We will develop using Microsoft Visual Studio, which is a very capable integrated
   development environment (IDE) that is quite accessible for CS&E and non-CS&E majors
   alike.
2. We will deploy our application prototypes using a development version of the standard
   Microsoft Internet Information Server (IIS), the standard Microsoft web server.
3. Our database will be Microsoft SQL Server,
   which includes Microsoft SQL Server
   Management Studio,
   a graphical front-end to the database manager itself.
4. Your web application will make heavy use of
   Microsoft’s =.Net= ("dot net") framework,
   including Active Server Pages (=ASP.Net=).
5. Your application will be written primarily in Microsoft Visual Basic
   and in Microsoft SQL Server stored procedures.
   Although the =.Net= platform supports
   other programming languages---notably =C#= ("see sharp")---we will stick
   with Visual Basic, which is full member of the =.Net= language family
   yet employs a clear and simple syntax that is easy for all students to learn.
* Classroom Expectations
Following are my expectations about classroom conduct.
** Attendance
Attendance is required. I will be in class each day,
and I expect you to be there also.
I will log who attends each class session.

In general, I am very understanding about students who must miss class
due to a sanctioned Taylor activity, job interview, family emergency, and the like.
If possible, let me know in advance if you will not be in class.
I will work with you to arrange make-up instruction, homework, exams, etc.
** Conduct
I expect you to be prepared, awake, aware, and participatory during class.
I will not hesitate to ask you to stand or move if you are distracted or sleepy.

I expect you to join in discussions,
respond to questions from me and from your colleagues,
and ask questions of me.
I expect you to hold my feet to the fire
if I am being unclear, unkind, or contradictory.
** Gizmos
You may not use a laptop, tablet, or similar device
to check e-mail, engage in social networking, surf the web,
or any other activity not directly relevant to current classroom activity.

If you use an electronic gizmo during class
for legitimate academic purposes (e.g., note taking),
be prepared to demonstrate relevant use on demand at any time.
*  Moodle
The Computer Science and Engineering department uses Moodle as our Learning Management
System. The URL for Moodle is https://cms.cse.taylor.edu. To sign on to the course site
for the first time, you will need an enrollment key. The key for this course is
=nerds4christ=.

You are responsible for checking Moodle regularly to keep up with assignment due dates and
other announcements posted to the site. For due dates, /the Moodle calendar is your friend/.
* Evaluation
The grading breakdown for the course is as follows:

#+ATTR_LATEX: :booktabs t
| Deliverable       | Weight |
|-------------------+--------|
|                   |    <r> |
| Labs and Homework |    20% |
| Term Project      |    40% |
| Midterm Exam      |    20% |
| Final Exam        |    20% |
|-------------------+--------|
| Total             |   100% |

Refer to the Periodic Table of the Grades (on Moodle) for my grading scheme.
I reserve the right to award a higher grade than strictly earned;
outstanding attendance and class participation
figure prominently in such decisions.
* Academic Integrity
As a student at an institution whose goal is to honor Christ in all that it does,
I expect you to uphold the strictest standards of academic integrity.
You must do your own work,
cite others when you present their work,
and never misrepresent your academic performance in any way.
Violation of these standards stains the reputations
of you as a student,
Taylor as an institution,
and Jesus as our Lord.
Such a violation will result in your failing the course
and other disciplinary action by the University.
Refer to the Taylor catalog for the official statement of these issues.

#+LATEX: \bibliographystyle{plain}
#+LATEX: \bibliography{courses}
