#+TITLE: SYS 390---Information Systems Analysis
#+DATE: Fall, 2014

#+STARTUP: indent
#+OPTIONS: toc:nil author:nil ':t

#+LATEX_CLASS: syllabus
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage[margin=1.5in]{geometry}
#+LATEX_HEADER: \usepackage{lastpage}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \lhead{SYS 390---Information Systems Analysis}
#+LATEX_HEADER: \chead{}
#+LATEX_HEADER: \rhead{Course Syllabus}
#+LATEX_HEADER: \lfoot{Fall 2014}
#+LATEX_HEADER: \cfoot{}
#+LATEX_HEADER: \rfoot{Page \thepage\ of \pageref{LastPage}}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0.4pt}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0.4pt}
#+LATEX_HEADER: \renewcommand\maketitle\relax

* Instructor
*Dr. Tom Nurkkala*\\
Associate Professor, Computer Science and Engineering\\
Director, Center for Missions Computing\\
Office: Euler Science 211\\
E-Mail: =tnurkkala@cse.taylor.edu=\\
Phone: 765/998-5163\\
Hours: MW 2:00-4:00 or by appointment\\

* Course Overview
In this course, you will acquire knowledge and develop skills
that will allow you to define and analyze an information system
using a software development methodology.
You will
undertake requirements analysis,
create data and process models,
design a user interface
and model user experience.
You will create a business proposal for an external customer's system,
and develop a comprehensive specification that meets the customer's requirements.
Your work in this course will be continued and completed in
SYS 394, Information Systems Design.

* Learning Objectives
Upon successful completion of this course, you should be able to:

+ Explain and apply the four absolutes of quality management
+ Explain the importance of knowing the business to successful systems analysis
+ Explain how project success depends on intelligent use of a software development
  methodology
+ Explain how system requirements and quality are related
+ Evaluate the return on investment of a project to assure real business value
+ Explain the role of information technology in business process re-engineering
+ Use Kepner-Tregoe decision analysis
+ Write well-posed requirements
+ Use a system response table to define project scope and decompose a system
+ Create use-cases that detail the user-focused capabilities of a system
+ Perform logical data modeling
+ Perform user experience modeling for a complex business application
+ Create wireframe mock-ups of an application

* Text
There is one required text for the course.\cite{valacich2012}
* Systems Analysis Project
The emphasis in this course is to /learn/ systems analysis by /doing/ systems analysis.
** Written Deliverables
Working with an external client,
you and your team
will analyze the client's business requirements
and produce two written deliverables:
1. A /business proposal/ (BP) that presents an analysis
   of the client's business requirements
   and enumerates proposed systems
   that address those requirements.
   A typical proposal
   offers both "build" and "buy" solutions,
   including a net-present-value analysis of each proposed solution.
   Based on several criteria (covered in class),
   your team will recommend the best solution for the client.
2. A /system requirements specification/ (SRS)
   that details a custom-built solution for the client's business requirements.
   In a commercial context, of course,
   you would only create an SRS
   if the business analysis recommended a "build" solution.
   However, because creating an SRS is a key learning in ISA,
   you will create the SRS regardless of the recommendation in your business proposal.
Your SRS will form the basis for building a working prototype of the system
that you will develop during SYS 394 (ISD) during the spring term.
** Formal Presentation
Your team will make a formal presentation of the your business proposal and SRS at the end
of the semester. The client is invited to attend your presentation. If the client is
unable to attend, I will stand in as a client proxy.

You are expected to arrive in business attire, make a professional quality presentation,
provide slides and handouts as required, and deliver high-quality printed copies of the
business proposal and SRS. Your team should be prepared to interact vigorously with the
client (or faculty proxy) to explain, clarify, and defend your analysis, proposal, and
SRS.

\newpage
* Evaluation

The grading breakdown for the course is as follows:
|----------+--------------------------+------------+-----+-----+-----|
| Homework |                          |            |     |     | 15% |
|----------+--------------------------+------------+-----+-----+-----|
| Project  |                          |            |     |     | 40% |
|          | Prelim Deliverables      |            |     | 10% |     |
|          | Final Deliverables       |            |     | 70% |     |
|          |                          | BP         | 30% |     |     |
|          |                          | SRS        | 70% |     |     |
|          | Presentation             |            |     | 20% |     |
|          |                          | Individual | 20% |     |     |
|          |                          | Team       | 80% |     |     |
|----------+--------------------------+------------+-----+-----+-----|
| Exams    |                          |            |     |     | 45% |
|          | Midterm 1                |            |     | 33% |     |
|          | Midterm 2                |            |     | 33% |     |
|          | Final (or project score) |            |     | 33% |     |
|----------+--------------------------+------------+-----+-----+-----|
Refer to my /Periodic Table of the Grades/ (on Moodle) for the grading scheme. I reserve
the right to award a higher grade than strictly earned; outstanding attendance and class
participation figure prominently in such decisions.
** Performance Appraisal
Early in the semester, your team will agree on a performance appraisal.
The performance appraisal lists criteria (e.g., "attends team meetings,"
"delivers on commitments") by which your team will evaluate itself at the end of the term.
Prior to your final presentation,
you will meet face-to-face as a team to evaluate one another according to these criteria.
Your team will submit your completed performance appraisal
at the time of your final presentation.

The performance appraisal is the key mechanism
by which you can hold fellow team members accountable to execute on the team project.
Although I evaluate the project on its merits,
the results of the appraisal determine how I apportion project credit
to each team member.
In other words,
I determine the size of the pie (total project points),
but you determine how the pie is sliced (individual point distribution)
** Final Exam
You may elect to take a final exam for the course.
However, you may elect to use your individual score from the team
project as your final exam score.

Most teams do well on the project.
Consequently, very few students elect to take the final exam.
Why offer this option? Consider these illustrative scenarios:
+ You're concerned that your project will not receive high marks
  (e.g., everyone else on your team spent way too much time rehearsing for Air Band).
  Doing well on the final could improve your grade in the course.
+ A team member (call him /Tom/) deserves a low score on the performance appraisal.
  As a graceful colleague, you're hesitant to evaluate Tom accurately
  because doing so will "cause" him to get a low overall course grade.
  However, because Tom could take the final and attempt to raise his grade,
  you're more willing to give honest feedback (benefiting Tom in the long run!).

Note the following regarding the final exam:
+ Projects are submitted at the end of the semester
  and are large and complex to grade.
  You will not have your final project grade
  before you have to decide whether or not to take the final.
+ Because few take the exam, it's normally conducted as an oral exam.
* Course Expectations
Following are my expectations regarding the course.
** Attendance
You are required to attend all class sessions.
I will be in class each day, and I expect you to be there also.

In general, I am very understanding about students who must miss class
due to a sanctioned Taylor activity, medical appointment, job interview,
family emergency, and the like.
If possible, let me know in advance that you will not be in class;
I will work with you to arrange make-up instruction, homework, exams, etc.
** Late Work
All course assignments will include an unambiguous due date.
Barring exceptional circumstances like those mentioned in section [[Attendance]],
I expect your work to be submitted /on the due date/.
Late work will /not/ be accepted.

This policy on late work is intended to prepare you
for real-world experience after graduation.
In the marketplace,
late work is not merely an inconvenience.
Missing a deadline may
alienate your customer,
upset your manager,
ruin your project,
or terminate your employment!
/Now/ is the time to learn the self discipline and time management skills
required to complete your work when it is due.
** Conduct
I expect you to be prepared, awake, aware, and participatory during class. I will not
hesitate to ask you to stand or move if you are distracted or sleepy.

I expect you to join in discussions, respond to questions from me and from your
colleagues, and ask questions of me. I expect you to hold my feet to the fire if I am
being unclear, unkind, or contradictory.
** Gizmos
You may not use a laptop, tablet, or similar device to check e-mail, engage in social
networking, surf the web, or any other activity not directly relevant
to current classroom activity.
If you use an electronic gizmo during class for legitimate academic purposes
(e.g., note taking), be prepared to demonstrate relevant use on demand
at any time.
* Moodle
The Computer Science and Engineering department uses Moodle as our Learning Management
System. The URL for Moodle is https://moodle.cse.taylor.edu. To sign on to the course site
for the first time, you will need an enrollment key. The key for this course is
=nerds4christ=.

You are responsible for checking Moodle regularly to keep up with assignment due dates and
other announcements posted to the site. For due dates, the Moodle calendar is your friend.
* Academic Integrity
As a student at an institution whose goal is to honor Christ in all that it does,
I expect you to uphold the strictest standards of academic integrity.
You must do your own work, cite others when you present their work,
and never misrepresent your academic performance in any way.
Violation of these standards stains the reputations of you as a student,
Taylor as an institution,
and Jesus as our Lord.
Such a violation may result in your failing the course
and other disciplinary action by the University.
Refer to the Taylor catalog for the official statement of these ideas.

#+LATEX: \bibliographystyle{plain}
#+LATEX: \bibliography{courses}
